// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hugo.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"highway-sign-portal-builder/pkg/models"
)

const getHugoCounties = `-- name: GetHugoCounties :many
SELECT id, county_name, county_slug, image_count, state_name, state_slug FROM sign.vwhugocounty
`

type GetHugoCountiesRow struct {
	ID         int32
	CountyName pgtype.Text
	CountySlug pgtype.Text
	ImageCount int64
	StateName  pgtype.Text
	StateSlug  pgtype.Text
}

func (q *Queries) GetHugoCounties(ctx context.Context) ([]GetHugoCountiesRow, error) {
	rows, err := q.db.Query(ctx, getHugoCounties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHugoCountiesRow
	for rows.Next() {
		var i GetHugoCountiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CountyName,
			&i.CountySlug,
			&i.ImageCount,
			&i.StateName,
			&i.StateSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHugoCountries = `-- name: GetHugoCountries :many
SELECT id, country_name, country_slug, subdivision_name, image_count, states, featured, highway_types FROM sign.vwhugocountry
`

func (q *Queries) GetHugoCountries(ctx context.Context) ([]SignVwhugocountry, error) {
	rows, err := q.db.Query(ctx, getHugoCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignVwhugocountry
	for rows.Next() {
		var i SignVwhugocountry
		if err := rows.Scan(
			&i.ID,
			&i.CountryName,
			&i.CountrySlug,
			&i.SubdivisionName,
			&i.ImageCount,
			&i.States,
			&i.Featured,
			&i.HighwayTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHugoFeatureLinks = `-- name: GetHugoFeatureLinks :many
SELECT id, id, from_feature, to_feature, road_name, highways, to_point, from_point FROM sign.vwhugofeaturelink
`

type GetHugoFeatureLinksRow struct {
	ID          int32
	ID_2        int32
	FromFeature pgtype.Int4
	ToFeature   pgtype.Int4
	RoadName    pgtype.Text
	Highways    interface{}
	ToPoint     interface{}
	FromPoint   interface{}
}

func (q *Queries) GetHugoFeatureLinks(ctx context.Context) ([]GetHugoFeatureLinksRow, error) {
	rows, err := q.db.Query(ctx, getHugoFeatureLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHugoFeatureLinksRow
	for rows.Next() {
		var i GetHugoFeatureLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.ID_2,
			&i.FromFeature,
			&i.ToFeature,
			&i.RoadName,
			&i.Highways,
			&i.ToPoint,
			&i.FromPoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHugoFeatures = `-- name: GetHugoFeatures :many
SELECT id, point, name, signs, state_name, state_slug, country_name, country_slug FROM sign.vwhugofeature
`

func (q *Queries) GetHugoFeatures(ctx context.Context) ([]SignVwhugofeature, error) {
	rows, err := q.db.Query(ctx, getHugoFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignVwhugofeature
	for rows.Next() {
		var i SignVwhugofeature
		if err := rows.Scan(
			&i.ID,
			&i.Point,
			&i.Name,
			&i.Signs,
			&i.StateName,
			&i.StateSlug,
			&i.CountryName,
			&i.CountrySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHugoHighwaySigns = `-- name: GetHugoHighwaySigns :many
SELECT id, title, sign_description, feature_id, date_taken, imageid, flickrid, point, country_slug, state_slug, place_slug, county_slug, tags, categories, highways, is_to, image_height, image_width, quality FROM sign.vwhugohighwaysign
`

func (q *Queries) GetHugoHighwaySigns(ctx context.Context) ([]SignVwhugohighwaysign, error) {
	rows, err := q.db.Query(ctx, getHugoHighwaySigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignVwhugohighwaysign
	for rows.Next() {
		var i SignVwhugohighwaysign
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SignDescription,
			&i.FeatureID,
			&i.DateTaken,
			&i.Imageid,
			&i.Flickrid,
			&i.Point,
			&i.CountrySlug,
			&i.StateSlug,
			&i.PlaceSlug,
			&i.CountySlug,
			&i.Tags,
			&i.Categories,
			&i.Highways,
			&i.IsTo,
			&i.ImageHeight,
			&i.ImageWidth,
			&i.Quality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHugoHighwayTypes = `-- name: GetHugoHighwayTypes :many
SELECT id, highway_type_name, highway_type_slug, sort, imagecount, imageid, highways, country FROM sign.vwhugohighwaytype
`

func (q *Queries) GetHugoHighwayTypes(ctx context.Context) ([]SignVwhugohighwaytype, error) {
	rows, err := q.db.Query(ctx, getHugoHighwayTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignVwhugohighwaytype
	for rows.Next() {
		var i SignVwhugohighwaytype
		if err := rows.Scan(
			&i.ID,
			&i.HighwayTypeName,
			&i.HighwayTypeSlug,
			&i.Sort,
			&i.Imagecount,
			&i.Imageid,
			&i.Highways,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHugoHighways = `-- name: GetHugoHighways :many
SELECT id, highway_name, slug, sort_number, image_name, highway_type_slug, highway_type_name, states, counties, places, previous_features, next_features FROM sign.vwhugohighway
`

func (q *Queries) GetHugoHighways(ctx context.Context) ([]SignVwhugohighway, error) {
	rows, err := q.db.Query(ctx, getHugoHighways)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SignVwhugohighway
	for rows.Next() {
		var i SignVwhugohighway
		if err := rows.Scan(
			&i.ID,
			&i.HighwayName,
			&i.Slug,
			&i.SortNumber,
			&i.ImageName,
			&i.HighwayTypeSlug,
			&i.HighwayTypeName,
			&i.States,
			&i.Counties,
			&i.Places,
			&i.PreviousFeatures,
			&i.NextFeatures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHugoPlaces = `-- name: GetHugoPlaces :many
SELECT id, place_name, place_slug, image_count, state_name, state_slug FROM sign.vwhugoplace
`

type GetHugoPlacesRow struct {
	ID         int32
	PlaceName  pgtype.Text
	PlaceSlug  pgtype.Text
	ImageCount int64
	StateName  pgtype.Text
	StateSlug  pgtype.Text
}

func (q *Queries) GetHugoPlaces(ctx context.Context) ([]GetHugoPlacesRow, error) {
	rows, err := q.db.Query(ctx, getHugoPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHugoPlacesRow
	for rows.Next() {
		var i GetHugoPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaceName,
			&i.PlaceSlug,
			&i.ImageCount,
			&i.StateName,
			&i.StateSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHugoStates = `-- name: GetHugoStates :many
SELECT id, state_name, state_slug, subdivision_name, image_count, highways, featured, country_slug, counties, places, categories FROM sign.vwhugostate
`

type GetHugoStatesRow struct {
	ID              int32
	StateName       pgtype.Text
	StateSlug       pgtype.Text
	SubdivisionName pgtype.Text
	ImageCount      int64
	Highways        []string
	Featured        pgtype.Int8
	CountrySlug     pgtype.Text
	Counties        []models.AdminArea
	Places          []models.AdminArea
	Categories      []string
}

func (q *Queries) GetHugoStates(ctx context.Context) ([]GetHugoStatesRow, error) {
	rows, err := q.db.Query(ctx, getHugoStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHugoStatesRow
	for rows.Next() {
		var i GetHugoStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.StateName,
			&i.StateSlug,
			&i.SubdivisionName,
			&i.ImageCount,
			&i.Highways,
			&i.Featured,
			&i.CountrySlug,
			&i.Counties,
			&i.Places,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
