// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	GetHugoCounties(ctx context.Context) ([]GetHugoCountiesRow, error)
	GetHugoCountries(ctx context.Context) ([]SignVwhugocountry, error)
	GetHugoFeatureLinks(ctx context.Context) ([]SignVwhugofeaturelink, error)
	GetHugoFeatures(ctx context.Context) ([]GetHugoFeaturesRow, error)
	GetHugoHighwayNames(ctx context.Context) ([]GetHugoHighwayNamesRow, error)
	GetHugoHighwaySigns(ctx context.Context) ([]SignVwhugohighwaysign, error)
	GetHugoHighwayTypes(ctx context.Context) ([]GetHugoHighwayTypesRow, error)
	GetHugoHighways(ctx context.Context) ([]GetHugoHighwaysRow, error)
	GetHugoPlaces(ctx context.Context) ([]GetHugoPlacesRow, error)
	GetHugoStates(ctx context.Context) ([]GetHugoStatesRow, error)
	GetHugoTags(ctx context.Context) ([]GetHugoTagsRow, error)
}

var _ Querier = (*Queries)(nil)
