languageCode = 'en-us'
title = 'Roadsign Pictures'
ignoreErrors = ["error-output-taxonomy"]
enableRobotsTXT = true

[outputFormats]
  [outputFormats.list]
    mediatype = "text/html"
    baseName = "list"
    isPlainText = false
    isHTML = true
    noUgly = false
    permalinkable = true

[taxonomies]
  tag = 'tags'
  highways = 'highway'
  counties = 'county'
  states = 'state'
  places = 'place'
  countries = 'country'
  recents = 'recent'

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/flowbite/dist"
    target = "assets/js/flowbite"
