baseURL = 'https://beta.roadsign.pictures'
languageCode = 'en-us'
title = 'Roadsign Pictures'
ignoreErrors = ["error-output-taxonomy"]
enableRobotsTXT = true

[taxonomies]
  tag = 'tags'
  highways = 'highway'
  counties = 'county'
  states = 'state'
  places = 'place'
  countries = 'country'
  recents = 'recent'
  geohashes = 'geohash'

[Params]
  W3WAPIKEY = 'dummy'

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "./node_modules/flickity/dist"
    target = "./assets/flickity"
