# fly.toml app configuration file generated for highway-sign-portal-ui-prod on 2023-11-12T08:15:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "highway-sign-portal-ui-prod"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]