services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/workspace
    stdin_open: true
  database:
    hostname: psql_db
    image: ghcr.io/zmaillard/rsp.db:v1.2.2
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
      - POSTGRES_DB=roadsign
