name: Deploy RoadSign Pictures
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.0'
    - run: go run main.go
      env:
        RSP_DB_USER: ${{ secrets.DB_USER }}
        RSP_DB_HOST: ${{ secrets.DB_HOST }}
        RSP_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        RSP_DB_PORT: ${{ secrets.DB_PORT }}
        RSP_DB_NAME: ${{ secrets.DB_NAME }}