name: Deploy RoadSign Pictures
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/manual.yaml'
    branches:
      - main
      - preview
jobs:
  version:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      tag: ${{ steps.bump-version.outputs.new_tag }}
      oldtag: ${{ steps.bump-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        id: bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          VERBOSE: true
          INITIAL_VERSION: 1.0.0
  deploy-staging:
    environment: Staging
    runs-on: ubuntu-latest
    needs: version
    if: github.ref == 'refs/heads/preview'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true
      - uses: actions/setup-node@v3
        with:
          node-version: '^16.17.1'
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
      - run: go run main.go
        env:
          RSP_DB_USER: ${{ secrets.DB_USER }}
          RSP_DB_HOST: ${{ secrets.DB_HOST }}
          RSP_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RSP_DB_PORT: ${{ secrets.DB_PORT }}
          RSP_DB_NAME: ${{ secrets.DB_NAME }}
      - run: npm install
      - run: npx tailwindcss -i ./assets/css/input.css -o ./assets/css/index.css --jit --minify
      - run: hugo --gc --minify --environment preview
        env:
          HUGO_PARAMS_W3WAPIKEY: ${{ secrets.HUGO_PARAMS_W3WAPIKEY }}
          HUGO_PARAMS_SEARCHINDEX: ${{ secrets.HUGO_PARAMS_SEARCHINDEX }}
          HUGO_PARAMS_SEARCHKEY: ${{ secrets.HUGO_PARAMS_SEARCHKEY }}
          HUGO_PARAMS_SEARCHURL: ${{ secrets.HUGO_PARAMS_SEARCHURL }}
          HUGO_PARAMS_VERSION: ${{ needs.version.outputs.oldtag }}
          HUGO_PARAMS_SIGNBASEURL: ${{ vars.HUGO_PARAMS_SIGNBASEURL }}
          HUGO_PARAMS_SHIELDBASEURL: ${{ vars.HUGO_PARAMS_SHIELDBASEURL }}
          HUGO_PARAMS_MAPTILE: ${{ vars.HUGO_PARAMS_MAPTILE }}
          HUGO_PARAMS_MAPBOXTOKEN: ${{ secrets.HUGO_PARAMS_MAPBOXTOKEN }}


      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy -c fly.staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-production:
    needs: version
    environment: Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true
      - uses: actions/setup-node@v3
        with:
          node-version: '^16.17.1'
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
      - run: go run main.go
        env:
          RSP_DB_USER: ${{ secrets.DB_USER }}
          RSP_DB_HOST: ${{ secrets.DB_HOST }}
          RSP_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RSP_DB_PORT: ${{ secrets.DB_PORT }}
          RSP_DB_NAME: ${{ secrets.DB_NAME }}

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: |
            kv:key put all --namespace-id 032a57eafe57449eb913b66b37af4801 --path data/images.json
            kv:key put county --namespace-id 032a57eafe57449eb913b66b37af4801 --path data/county.json
            kv:key put place --namespace-id 032a57eafe57449eb913b66b37af4801 --path data/place.json
            kv:key put state --namespace-id 032a57eafe57449eb913b66b37af4801 --path data/state.json

      - run: npm install

      - run: npx tailwindcss -i ./assets/css/input.css -o ./assets/css/index.css --jit --minify

      - run: hugo --gc --minify  --environment production
        env:
          HUGO_PARAMS_W3WAPIKEY: ${{ secrets.HUGO_PARAMS_W3WAPIKEY }}
          HUGO_PARAMS_SEARCHINDEX: ${{ secrets.HUGO_PARAMS_SEARCHINDEX }}
          HUGO_PARAMS_SEARCHKEY: ${{ secrets.HUGO_PARAMS_SEARCHKEY }}
          HUGO_PARAMS_SEARCHURL: ${{ secrets.HUGO_PARAMS_SEARCHURL }}
          HUGO_PARAMS_VERSION: ${{ needs.version.outputs.tag }}
          HUGO_PARAMS_SIGNBASEURL: ${{ vars.HUGO_PARAMS_SIGNBASEURL }}
          HUGO_PARAMS_SHIELDBASEURL: ${{ vars.HUGO_PARAMS_SHIELDBASEURL }}
          HUGO_PARAMS_MAPTILE: ${{ vars.HUGO_PARAMS_MAPTILE }}
          HUGO_PARAMS_MAPBOXTOKEN: ${{ secrets.HUGO_PARAMS_MAPBOXTOKEN }}

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy -c fly.production.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - run: flyctl deploy -c fly.toml --remote-only
        working-directory: tiles
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_MAP_TILE }}

