name: pr.yaml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  generate-test-data:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ghcr.io/zmaillard/rsp.db:v1.1.1
        env:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: rsp
            POSTGRES_DB: roadsign
            POSTGRES_HOST: localhost
        ports:
            - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.139.0'
          extended: true
      - uses: actions/setup-node@v3
        with:
          node-version: '^16.17.1'
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
      - run: go run main.go
        env:
          RSP_DATABASE_URL: postgresql://admin:rsp@localhost/roadsign'
      - run: npm install
      - run: npx tailwindcss -i ./assets/css/input.css -o ./assets/css/index.css --jit --minify
      - run: hugo --gc --minify --environment development
        env:
          HUGO_PARAMS_SEARCHINDEX: ${{ secrets.HUGO_PARAMS_SEARCHINDEX }}
          HUGO_PARAMS_SEARCHINDEXHIGHWAY: ${{ vars.HUGO_PARAMS_SEARCHINDEXHIGHWAY }}
          HUGO_PARAMS_SEARCHKEY: ${{ secrets.HUGO_PARAMS_SEARCHKEY }}
          HUGO_PARAMS_SEARCHURL: ${{ secrets.HUGO_PARAMS_SEARCHURL }}
          HUGO_PARAMS_VERSION: 'v1.0.0'
          HUGO_PARAMS_SIGNBASEURL: ${{ vars.HUGO_PARAMS_SIGNBASEURL }}
          HUGO_PARAMS_SHIELDBASEURL: ${{ vars.HUGO_PARAMS_SHIELDBASEURL }}
          HUGO_PARAMS_MAPTILE: ${{ vars.HUGO_PARAMS_MAPTILE }}
          HUGO_PARAMS_MAPBOXTOKEN: ${{ secrets.HUGO_PARAMS_MAPBOXTOKEN }}
          HUGO_PARAMS_RANDOMURL: ${{ vars.HUGO_PARAMS_RANDOMURL }}
