name: Deploy Random Sign Worker
on:
  push:
    paths:
      - random/**
    branches:
      - main
jobs:
  - uses: cloudflare/wrangler-action@v3
    with:
      apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      workingDirectory: random
      command: |
        deploy --minify src/index.ts
